### ISSUE TITLE
Assignments take excessively long to scrape

### ISSUE THREAD

**Issue by kevin3-black** [project-manatee/manatee-android#20]
A change by AISD made it so that the scraper must make a POST request to the averages page each time before requesting the assignments page. However, even accounting for that, it seems like the assignments are taking forever to load. Not sure if nothing can be done about it or if it's an inefficiency with the app/scraper.

**Comment by ehsanmasdar** [comment]
@kevin3-black Define "forever." Scraping was always pretty slow due to server speed. There's also a couple of optimizations that were made to limit mobile data usage.

**Comment by kevin3-black** [comment]
@ehsanmasdar Anywhere from 8-16 seconds per class on my home WiFi, which is currently getting about 60 Mbps (although I that shouldn't be a relevant limitation). I don't recall it being that slow before, and the averages only take 2-3 seconds to load or refresh.

**Comment by patil215** [comment]
Does accessing TEAMS normally (i.e. through desktop) also take longer to load assignments? If so, there's no great solution. One improvement that could be done is to more aggressively load in the background (by lowering the background polling interval, or moving it to poll grades right before the user is likely to open the app (such as 8 am or 2 pm, etc).

**Comment by ehsanmasdar** [comment]
If we are talking all cycles of a certain class, this time sounds right to me. We basically eliminated all foreground loading of teams pages unless the user explicitly demands refresh because the server is so slow (and even in the background, it only refreshes class pages if your cycle average changes). 

In regards to initial loading, when you first login a process is kicked off to start loading all class grades. If the user is faster than this background task and selects a class that is not yet loaded yet the dialog is kicked to the foreground until the class is done loading. I agree with @patil215 you probably want to profile the loading time on Desktop and compare. Something else to consider: TEAMS also may be throttling us/throttling any user that requests more than a certain number of pages in a certain time frame.
